[package]
name = "daedalus"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { version = "0.5.1", features = ["app_utils"] }
egui = "0.33.0"

#egui_tiles = "0.12.0" # For layouts etc. Experimenting
egui-file-dialog = "0.12.0" #  For file dialogs.
egui_plot = "0.34.0"  # For Rama plots

cfg-if = "1.0.1"

lin_alg = { version = "1.3.10", features = ["encode"] }
na_seq = "0.3.8"
bio_apis = {  version = "0.1.10", features = ["encode"] }
bio_files = "0.3.0"
mcubes = "0.1.6"
#dynamics = { version = "0.1.0", features = ["encode"] }
dynamics = { path = "../dynamics", features = ["encode"] }

# For loading and saving config
bincode = "2.0.1"
rayon = "1.10.0"  # Parallel execution on CPU using thread pools.


rand = "0.9.2"
regex = "1.11.1"
chrono = "0.4.41"

# Note: This section must be at the bottom; applies to all elements below it.
[target.'cfg(not(target_os = "windows"))'.dependencies]
cudarc = { version = "0.17.2", default-features = false, features = ["std", "driver", "dynamic-linking", "cuda-13000"], optional=true }
# Note: The non-cuda one seems to work on a non-nvidia Win with dynamic-linking.
[target.'cfg(target_os = "windows")'.dependencies]
cudarc = { version = "0.17.2", default-features = false, features = ["std", "driver", "dynamic-linking", "cuda-13000"], optional=true }


# We use these when developing locally to reduce friction.
[patch.crates-io]
#graphics = { path = "../graphics" }
#lin_alg = { path = "../../lin_alg" }
#na_seq = { path = "../na_seq" }
bio_apis = { path = "../bio_apis" }
#mcubes = { path = "../mcubes" }
bio_files = { path = "../bio_files" }
dynamics = { path = "../dynamics" }


[build-dependencies]
cuda_setup = { version = "0.1.9", optional = true }
# This is for embedding an application icon, on Windows.
winresource = "0.1.20"

# We feature-gate the CUDA dependency, so this program can be run on computers that don't have a
# suitable graphics chip.
[features]
default = ["cuda"]

#cuda = ["cuda_setup", "cudarc", "lin_alg/cuda", "dynamics/cuda", "dynamics/vkfft"]
cuda = ["cuda_setup", "cudarc", "lin_alg/cuda", "dynamics/cuda", "dynamics/cufft"]


[profile.release]
strip = true  # Strip symbols from binary. Size reduction on Linux/Mac.