[package]
name = "daedalus"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { version = "0.4.0", features = ["app_utils"] }
egui = "0.31.1"
#egui_tiles = "0.12.0" # For layouts etc. Experimenting
egui-file-dialog = "0.10.0" #  For file dialogs.

cfg-if = "1.0.0"

lin_alg = { version = "1.1.10", features = ["encode"] }
# todo: Use https://github.com/bempp/kifmm when ready? Adapt for Windows.
barnes_hut = { version = "1.0.8"}  # enc temp rem
# todo: Qhull is temp until we find a way to generate non-convex meshes.
# todo: Relies on C FFI. This may complicate compiling.
#qhull = "0.4.0"
na_seq = "0.2.7"
bio_apis = {  version = "0.1.2", features = ["encode"] }
bio_files = "0.1.0"
#bio_files = { path = "../bio_files" }

# For loading and saving config
bincode = "2.0.1"
rayon = "1.10.0"  # Parallel execution on CPU using thread pools.
# Keep this cuda version in sync with what you have installed on the system.

# todo: Do we want the `dynamic-linking` cudarc feature? Instead of dynamic-loading?
# todo: If you use it, rem def features, and add specifically the other defaults.
cudarc = { version = "0.16.4", features = ["cuda-version-from-build-system"], optional=true }
#cudarc = { version = "0.16.4", features = [
#    "std", "cublas", "cublaslt", "curand", "driver", "runtime", "nvrtc", "dynamic-linking"
#], default-features = false, optional=true }

# For reading PDB and mmCIF files
pdbtbx = "0.12.0"
rand = "0.9.1"
regex = "1.11.1"

# nalgebra: For solving linear systems of equations when generating partial changes.
nalgebra = "0.33.2"

mcubes = "0.1.1"


# We use these when developing locally to reduce friction.
[patch.crates-io]
graphics = { path = "../../graphics" }
#lin_alg = { path = "../../lin_alg" }
pdbtbx = { git = "https://github.com/David-OConnor/pdbtbx", branch = "Fix-symmetry-error-newer-CIFs" }
#barnes_hut = { path = "../../barnes_hut" }
na_seq = { path = "../na_seq" }
bio_apis = { path = "../bio_apis" }
mcubes = { path = "../mcubes" }
bio_files = { path = "../bio_files" }



[build-dependencies]
cuda_setup = { version = "0.1.4", optional = true }
# This is for embedding an application icon, on Windows.
winresource = "0.1.20"

# We feature-gate the CUDA dependency, so this program can be run on computers that don't have a
# suitable graphics chip.
[features]
default = ["cuda"]

cuda = ["cuda_setup", "cudarc", "lin_alg/cuda"]


[profile.release]
strip = true  # Strip symbols from binary. Size reduction on Linux/Mac.